[[IgnoredVulns]]
id = "GHSA-q7pp-wcgr-pffx"
reason = "No impact since we don't work with TIFF image files"
[[IgnoredVulns]]
id = "GO-2024-2521"
reason = "Data seems wrong, reported at https://github.com/google/osv.dev/issues/2389"